spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false